jaffle_shop_parquet:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: my comment
      role_arn: arn:aws:iam::123456789101:role/AWSGlueServiceRole-dbt
      region: eu-west-1
      workers: 2
      worker_type: G.1X
      schema: "jaffle_shop_schema"
      session_provisioning_timeout_in_seconds: 120
      location: "s3://demo-dbt-glue-123456789101"
      datalake_formats: iceberg
      glue_session_reuse: True

jaffle_shop_iceberg:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: my comment
      role_arn: arn:aws:iam::123456789101:role/AWSGlueServiceRole-dbt
      region: eu-west-1
      workers: 2
      worker_type: G.1X
      schema: "jaffle_shop_schema"
      session_provisioning_timeout_in_seconds: 120
      location: "s3://demo-dbt-glue-123456789101/jaffle_shop_schema"
      datalake_formats: iceberg
      glue_session_reuse: True
      conf: spark.sql.catalog.glue_catalog=org.apache.iceberg.spark.SparkCatalog  --conf spark.sql.catalog.glue_catalog.warehouse=s3://demo-dbt-glue-123456789101/jaffle_shop_schema --conf spark.sql.catalog.glue_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog --conf spark.sql.catalog.glue_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions  

jaffle_shop_hudi:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: my comment
      role_arn: arn:aws:iam::123456789101:role/AWSGlueServiceRole-dbt
      region: eu-west-1
      workers: 2
      worker_type: G.1X
      schema: "jaffle_shop_schema"
      session_provisioning_timeout_in_seconds: 120
      location: "s3://demo-dbt-glue-123456789101"
      datalake_formats: hudi
      glue_session_reuse: True
      conf: spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.sql.hive.convertMetastoreParquet=false


jaffle_shop_delta:
  target: dev
  outputs:
    dev:
      type: glue
      query-comment: my comment
      role_arn: arn:aws:iam::123456789101:role/AWSGlueServiceRole-dbt
      region: eu-west-1
      workers: 2
      worker_type: G.1X
      schema: "jaffle_shop_schema"
      session_provisioning_timeout_in_seconds: 120
      location: "s3://demo-dbt-glue-123456789101"
      datalake_formats: delta
      glue_session_reuse: True
      conf: spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
